### ISSUE TITLE
Save large data to a file xlsx

### ISSUE THREAD

**Issue by AkinMax** [ggreen86/XLSX-Workbook-Class#124]
Hello.
I try to save cursor with 400 000 records and 20 columns to xlsx file.
But when I open the excel file, it reports that the file is corrupted, and it's empty.
Is it possible to fix this problem?
I am using version 44
Thanks.
Akin

**Comment by ggreen86** [comment]
Probably the cause is the sheet1.xml file is greater than 2G and VFP cannot handle that size file.  This is a limitation of VFP and not the class.

From: AkinMax ***@***.***>
Sent: Thursday, September 26, 2024 7:30 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Save large data to a file xlsx (Issue #124)


Hello.
I try to save cursor with 400 000 records and 20 columns to xlsx file.
But when I open the excel file, it reports that the file is corrupted, and it's empty.
Is it possible to fix this problem?
I am using version 44
Thanks.
Akin

**Comment by AkinMax** [comment]
The problem occurs when the text in the data is written in russian cyrillic.
The code is bellow.
```
Set Classlib To VFPxWorkbookXLSX
Local lcFile
lcFile = Fullpath(Sys(5)+Sys(2003)+'\test_bigdata.xlsx')
Create Cursor test_big (field1 c(200),field2 c(200))
For nCOUNT = 1 To 400000
	Insert Into test_big (field1,field2) ;
		Values ;
		(Replicate('é',200),Replicate('t',200))
Endfor
lcAlias = 'test_big'
Select &lcAlias
loExcel   = Newobject("VFPxWorkbookXLSX", "VFPxWorkbookXLSX.vcx")
loExcel.Savetabletoworkbookex(lcAlias, lcFile, .Null., .T., lcAlias)
Release loExcel
Messagebox('end of processing')
```

**Comment by ggreen86** [comment]
Set the codepage property as appropriate for Russian.  It defaults to western.

**Comment by AkinMax** [comment]
I have set the code page 1251
anyway the file is corrupted
When I change to 300000 records, file ist correct
```
For nCOUNT = 1 To 300000
...
```

**Comment by ggreen86** [comment]
Please send me the generated file.  Please be sure to not include any sensitive information.  Thank you.

**Comment by AkinMax** [comment]
[TEST_BIGDATA.xlsx](https://github.com/user-attachments/files/17185637/TEST_BIGDATA.xlsx)

**Comment by ggreen86** [comment]
I was able to open enough of the file to determine the cause.  The Russian text is not being flagged correctly for the xml file as a UTF-8.  Seems it is only being saved as a standard ASCII.  I am going to send you a modified class to add some debugging to try to determine if the file is being marked.

**Comment by ggreen86** [comment]
Please create the same Test_BigData.xlsx file with the attached class code.  I have added some debugging steps in the sheet creation method.  This will generate a file "DebugUTF8.txt"; please send this to me.  Basically, the problem is the sheet?.xml files are not being identified as UTF-8; the file should have the hex characters EF BB BF at the beginning of the file.  Instead, it is being interpreted as an ASCII file and it is failing with the Russian characters in the first text cell.

[DebugWorkbookXLSX.zip](https://github.com/user-attachments/files/17191655/DebugWorkbookXLSX.zip)

**Comment by AkinMax** [comment]
the file was not created on the disk

**Comment by AkinMax** [comment]
[TEST_300_rows.xlsx](https://github.com/user-attachments/files/17191858/TEST_300_rows.xlsx)

**Comment by ggreen86** [comment]
The test_300_rows.xlsx file opened without errors; however, the cell text does not look to me to be correct.  Please open the class and method WriteSheetXMLs().  Check lines 963, 973, and 977.  These should contain STRTOFILE() commands and be commented with "&& Debugging code".  This should create the file in the default directory of the running program.

If you find it, the method should have processed correctly as the above file opened (meaning that the method SaveAsUTF8 completed correctly).  Please re-run with the TEST_BIGDATA and then send the debug log file.

**Comment by ggreen86** [comment]
I added some more debugging code to the class.  Please use this class version and re-run the code to generate TEST_BIGDATA.xlsx file.  Please send me the "DebugUTF8.txt" file that should be created in the current default directory of the program.

[DebugWorkbookXLSX.zip](https://github.com/user-attachments/files/17193068/DebugWorkbookXLSX.zip)

**Comment by AkinMax** [comment]
[DebugUTF8.txt](https://github.com/user-attachments/files/17193217/DebugUTF8.txt)

**Comment by ggreen86** [comment]
I think the problem is that you are exceeding the 2G limit or there is not enough memory allocated to VFP.  The program is trying to reopen the created file from the FWRITE commands in order to convert the double-byte characters to UTF-8 and then saving back to the file.  I am guessing that VFP when doing the convert is running out of memory since both the original string and the converted string is both in memory.

I am going to try a different strategy of conversion.  Instead of opening the entire file with FILETOSTR command, I am going to use FOPEN and FREAD to limit the size being converted with a subsequent FWRITE.  I will let you know when I have a working class with this change.

**Comment by AkinMax** [comment]
Thank's.
I'll be waiting for the change in the code

**Comment by ggreen86** [comment]
I have made the change and tested on my system.  The files seem to be converted without problems to UTF-8.  Please try again with this attached version of the class.

[DebugWorkbookXLSX.zip](https://github.com/user-attachments/files/17193742/DebugWorkbookXLSX.zip)

**Comment by AkinMax** [comment]
Hello
It works
Thank you very much.

**Comment by ggreen86** [comment]
This issue is fixed.  Next release will incorporate this fix (R46).
