### ISSUE TITLE
Git project has a typo in the name

### ISSUE THREAD

**Issue by DanLauer** [ggreen86/XLSX-Workbook-Class#15]
This might not really be a big deal, but the Git project should be XLSX-Workbook-Class rather than XLXS-Workbook-Class.

**Comment by bzaner** [comment]
Would you assist?  If so, what would you charge?

 

What I’m using now, since I could not make that work is:

 

FUNCTION xlsxout

PARAMETERS inpfile,filenam

select &inpfile

COPY TO &filenam TYPE csv

m.filename = FULLPATH(filenam)

cInFILE = ALLTRIM(UPPER(m.filename))

cOUTFILE = STRTRAN(cInFile, ".CSV", ".XLSX")

IF FILE(cOUTFILE)

  ERASE (cOUTFILE)

ENDIF 

oExcel = createobject('Excel.Application')

oWorkbook  = oExcel.application.workbooks.open(cInFile)

xlOpenXMLWorkbook = 51

oWorkbook.saveas(cOUTFILE, xlOpenXMLWorkbook)

oWorkbook.close(.T.)

oExcel.quit()

oExcel = .null.

oWorkbook = .null.

IF FILE(cInFILE)

  ERASE (cInFILE)

ENDIF 

RETURN

 

 

Thanks,

 

Byron

_______________________________

Construction Software…

                        …turning your time into profit




 

Direct: 702-703-4836

 

Toll  Free: 888-394-0252

                http://www.priosoft.com

                     <https://www.facebook.com/priosoft/> f   <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.linkedin.com%2fcompany%2f1545521%3ftrk%3dtyah&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=d8N7U2LHl2tvFcxzVSJxPh9r4YM%2fxHU%2fEVv719fq07o%3d>   <https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2ftwitter.com%2fpriosoft&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=RLbGW3sfRJcBF25ZpTn5ue6MbG6xTWtmDTbUjXFOWhU%3d>  <https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fplus.google.com%2f105070244357160453152%2fposts&data=01%7c01%7csakris%40064d.mgd.microsoft.com%7ce6313a46af2f4df9d42108d352be3a92%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=33ZP%2b5GfXP1oQbxDxP3AYglacR4Kff1MvImO8aM%2fqcQ%3d>   <https://www.youtube.com/c/priosoft>  

 

From: bzaner@priosoft.com <bzaner@priosoft.com> On Behalf Of Dan Lauer
Sent: Tuesday, March 20, 2018 12:46 PM
To: ggreen86/XLXS-Workbook-Class <XLXS-Workbook-Class@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [ggreen86/XLXS-Workbook-Class] Git project has a typo in the name (#15)

 

This might not really be a big deal, but the Git project should be XLSX-Workbook-Class rather than XLXS-Workbook-Class.

**Comment by DanLauer** [comment]
This appears to have been fixed.
