### ISSUE TITLE
Support XLSM file

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#24]
I tried to output to a file using XLSM as the extension and XLSXWorkbook forced the extension to XLS. The reason I want to do this is because I have a customer with an existing XLSM file they want to append another worksheet to.

**Comment by ggreen86** [comment]
Doug--

I looked at what would be needed to support the XLSM file.  It is not as simple just adding a new sheet or changing a sheet and then saving with a XLSM extension.  This type has more components that would have to be changed.  So it is now on the 'radar' to add as a feature, but I am not sure when as my time is limited right now due to current project work.

Greg
