### ISSUE TITLE
Rewriting index prompt

### ISSUE THREAD

**Issue by SeregaKR** [ggreen86/XLSX-Workbook-Class#35]
Testing new version of the class. Found this bug:
```
CREATE CURSOR xl_sheets (_long line of fields here_ )
INDEX ON sheet TAG sheet
INDEX ON workbook TAG workbook
INDEX ON BINTOC(workbook)+UPPER(ALLTRIM(shname)) TAG shname
**INDEX ON BINTOC(workbook)+BINTOC(sheet) TAG sheet FOR !DELETED()**
SET INDEX TO
```
During testing found out that every time it asks me to rewrite index on the bold line. The name of the index is the same.  Renamed to wbsheet as in the next cases.

Otherwise it works much faster. After fixing this I see no other issues

**Comment by ggreen86** [comment]
I had already found that bug (found by another user); thank you for the report.  However, you commented out the wrong tag.  The first sheet tag should be deleted.

________________________________

**Comment by SeregaKR** [comment]
I was just highlighting the row with * symbol. I changed the code to this:
```
INDEX ON sheet TAG sheet
INDEX ON workbook TAG workbook
INDEX ON BINTOC(workbook)+UPPER(ALLTRIM(shname)) TAG shname
INDEX ON BINTOC(workbook)+BINTOC(sheet) TAG wbsheet FOR !DELETED()
SET INDEX TO
```
Later I saw the same tag in other cursors named like this.

**Comment by ggreen86** [comment]
Do not change the tag name.  Delete the first SET INDEX line; the result should be

INDEX ON workbook TAG workbook
INDEX ON BINTOC(workbook)+UPPER(ALLTRIM(shname)) TAG shname
INDEX ON BINTOC(workbook)+BINTOC(sheet) TAG sheet FOR !DELETED()
SET INDEX TO


This is due to SEEK() statements that expect the BINTOC(workbook)+BINTOC(sheet) expression and the tag name sheet. Your change will break a lot of code.


________________________________

**Comment by SeregaKR** [comment]
Ok. Noted. Thank you for an answer.
I changed the tag name because it's like this in the several other cursors below.
