### ISSUE TITLE
Error setCellBorderex

### ISSUE THREAD

**Issue by alcidesrss** [ggreen86/XLSX-Workbook-Class#41]
Hi Greg,
I am using google translate
Using setcellborderex an error was generated, "Too many arguments"
Compare version 31 with version 32 and version 32 has a value of more, I show you in the images.

![image](https://user-images.githubusercontent.com/58947268/114777545-6ea5fa00-9d39-11eb-89c4-9fe78ee4c331.png)

Version 31
![image](https://user-images.githubusercontent.com/58947268/114777597-78c7f880-9d39-11eb-9fb3-7281f4f1eaa7.png)

Version 32
![image](https://user-images.githubusercontent.com/58947268/114777653-7f567000-9d39-11eb-9e13-8ae43fb4b9fb.png)

It is an excellent tool, thank you.

**Comment by ggreen86** [comment]
Thank you for your time to notify me of the bug.  It is now fixed in beta 3.  By the way, take a look at the documentation on page 13 and starting at page 42 for Cell Styles.  This technique of setting the cell formatting has less overhead and as such is faster.

Greg

________________________________
From: alcidesrss ***@***.***>
Sent: Wednesday, April 14, 2021 4:55 PM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Error setCellBorderex (#41)


Hi Greg,
I am using google translate
Using setcellborderex an error was generated, "Too many arguments"
Compare version 31 with version 32 and version 32 has a value of more, I show you in the images.

[image]<https://user-images.githubusercontent.com/58947268/114777545-6ea5fa00-9d39-11eb-89c4-9fe78ee4c331.png>

Version 31
[image]<https://user-images.githubusercontent.com/58947268/114777597-78c7f880-9d39-11eb-9fb3-7281f4f1eaa7.png>

Version 32
[image]<https://user-images.githubusercontent.com/58947268/114777653-7f567000-9d39-11eb-9e13-8ae43fb4b9fb.png>

It is an excellent tool, thank you.
