### ISSUE TITLE
Protection

### ISSUE THREAD

**Issue by lscheffler** [ggreen86/XLSX-Workbook-Class#49]
There are methods to protect / unprotect objects (workbook / sheet.   
This sets a bunch of props, 
I see stuff like _AlgorithmName_
Does this encrypt / decrypt or is this just a setting for Excel to not touch the cells? IOW, cann I alter the cells ignoring the protection?

**Comment by ggreen86** [comment]
There is not actually any encryption going on to the cell values.  This class actually bypasses any that Excel would enforce since you have direct access to the cells via the methods.  The formatting of the cells is what controls the protection setting; the sheet setting controls whether it is enforced by Excel (the class ignores the setting).  If you reassign the cell formatting, it could alter the protection setting of the cell.  The password is what is encrypted into the workbook; not the actual cell values.

________________________________
From: Lutz Scheffler ***@***.***>
Sent: Friday, May 14, 2021 12:17 PM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Protection (#49)


There are methods to protect / unprotect objects (workbook / sheet.
This sets a bunch of props,
I see stuff like AlgorithmName
Does this encrypt / decrypt or is this just a setting for Excel to not touch the cells? IOW, cann I alter the cells ignoring the protection?

**Comment by lscheffler** [comment]
ok. So I can just ignore this. It's just about gathering some data from those cells (I'm in my general manager and there is a unprotect step.)
