### ISSUE TITLE
Only change SET POINT and SET SEPARATOR if necessary

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#56]
The SET POINT and SET SEPARATOR commands are very slow. It isn't noticeable when creating a small spreadsheet but if there are thousands of records with lots of columns, it can slow down creation a lot.

I changed SaveVFPSettings to the following so these settings are only changed if necessary:

```
*** DH 2021-06-21: only change settings if necessary
*	SET POINT TO "."
*	SET SEPARATOR TO ","
	if this.VFPSettings.SetPoint <> '.'
		SET POINT TO "."
	else
		this.VFPSettings.SetPoint = ''
	endif
	if this.VFPSettings.Separator <> ','
		SET SEPARATOR TO ","
	else
		this.VFPSettings.Separator = ''
	endif
*** DH 2021-06-21: end of change
```

Similarly, in RestoreVFPSettings:

```
	lxSetting = this.VFPSettings.SetPoint
*** DH 2021-06-21: only change settings if necessary
*	SET POINT TO (lxSetting)
	if not empty(lxSetting)
		SET POINT TO (lxSetting)
	endif
	
	lxSetting = this.VFPSettings.Separator
*	SET SEPARATOR TO (lxSetting)
	if not empty(lxSetting)
		SET SEPARATOR TO (lxSetting)
	endif
*** DH 2021-06-21: end of change
```

**Comment by ggreen86** [comment]
Doug--

Thank you for the find -- did you find it using the profiler tool?  I have not yet released the class as non-Beta since I found some errors in the bookmarks in the main documentation that I have yet to fix.  So, I have added the zip as the next beta to VFPx site.

Greg

________________________________
From: Doug Hennig ***@***.***>
Sent: Monday, June 21, 2021 10:42 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Only change SET POINT and SET SEPARATOR if necessary (#56)


The SET POINT and SET SEPARATOR commands are very slow. It isn't noticeable when creating a small spreadsheet but if there are thousands of records with lots of columns, it can slow down creation a lot.

I changed SaveVFPSettings to the following so these settings are only changed if necessary:

*** DH 2021-06-21: only change settings if necessary

  *   SET POINT TO "."
  *   SET SEPARATOR TO ","
if this.VFPSettings.SetPoint <> '.'
SET POINT TO "."
else
this.VFPSettings.SetPoint = ''
endif
if this.VFPSettings.Separator <> ','
SET SEPARATOR TO ","
else
this.VFPSettings.Separator = ''
endif
*** DH 2021-06-21: end of change

Similarly, in RestoreVFPSettings:

lxSetting = this.VFPSettings.SetPoint


*** DH 2021-06-21: only change settings if necessary

  *   SET POINT TO (lxSetting)
if not empty(lxSetting)
SET POINT TO (lxSetting)
endif

lxSetting = this.VFPSettings.Separator

  *   SET SEPARATOR TO (lxSetting)
if not empty(lxSetting)
SET SEPARATOR TO (lxSetting)
endif
*** DH 2021-06-21: end of change

**Comment by DougHennig** [comment]
Hi Greg.

 

No, a customer reported this as an issue a couple of years ago and you had changed it, but when you rewrote the code into separate methods you likely missed the reason for checking the current values.

 

Doug

 

From: ggreen86 ***@***.***> 
Sent: June 21, 2021 12:46 PM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Doug Hennig ***@***.***>; Author ***@***.***>
Subject: SPAM-LOW: Re: [ggreen86/XLSX-Workbook-Class] Only change SET POINT and SET SEPARATOR if necessary (#56)

 

Doug--

Thank you for the find -- did you find it using the profiler tool? I have not yet released the class as non-Beta since I found some errors in the bookmarks in the main documentation that I have yet to fix. So, I have added the zip as the next beta to VFPx site.

Greg

________________________________
From: Doug Hennig ***@***.*** <mailto:***@***.***> >
Sent: Monday, June 21, 2021 10:42 AM
To: ggreen86/XLSX-Workbook-Class ***@***.*** <mailto:***@***.***> >
Cc: Subscribed ***@***.*** <mailto:***@***.***> >
Subject: [ggreen86/XLSX-Workbook-Class] Only change SET POINT and SET SEPARATOR if necessary (#56)


The SET POINT and SET SEPARATOR commands are very slow. It isn't noticeable when creating a small spreadsheet but if there are thousands of records with lots of columns, it can slow down creation a lot.

I changed SaveVFPSettings to the following so these settings are only changed if necessary:

*** DH 2021-06-21: only change settings if necessary

* SET POINT TO "."
* SET SEPARATOR TO ","
if this.VFPSettings.SetPoint <> '.'
SET POINT TO "."
else
this.VFPSettings.SetPoint = ''
endif
if this.VFPSettings.Separator <> ','
SET SEPARATOR TO ","
else
this.VFPSettings.Separator = ''
endif
*** DH 2021-06-21: end of change

Similarly, in RestoreVFPSettings:

lxSetting = this.VFPSettings.SetPoint


*** DH 2021-06-21: only change settings if necessary

* SET POINT TO (lxSetting)
if not empty(lxSetting)
SET POINT TO (lxSetting)
endif

lxSetting = this.VFPSettings.Separator

* SET SEPARATOR TO (lxSetting)
if not empty(lxSetting)
SET SEPARATOR TO (lxSetting)
endif
*** DH 2021-06-21: end of change

**Comment by ggreen86** [comment]
This is 're-fixed' in Release 33 beta 10.  Thank you.
