### ISSUE TITLE
Support Windows 10 in AddFilesToZip

### ISSUE THREAD

**Issue by Starfiresg1** [ggreen86/XLSX-Workbook-Class#57]
In order to properly detect Windows 10 I had to make the following change to AddFilesToZip:

Old:
`IF VAL(VERSION(4)) <= 9 .AND. (OS(3)<'6' .OR. OS(3)='6' .AND. OS(4)<'1')`

New:
`IF VAL(VERSION(4)) <= 9 .AND. (VAL(OS(3))<6 .OR. VAL(OS(3))=6 .AND. VAL(OS(4))<1)`

Background:
While by default OS() will not report the correct information under Windows 10, it is possible to make it report the correct values for Windows 10, e.g. OS(3)='10', if the app is using an application manifest declaring itself Windows 10 aware.
This is propably due to Foxpro using the GetVersionEx-API to determine this value - starting with Windows 8.1 this API will only report Windows 8 numbers unless the manifest specifies comaptibility with higher Windows versions - see [https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa).

The comparison fails then because the values are compared as strings - which results in '10'<'6' as evaluating as .T.. Casting the results to numerical values and comparing numerically will fix this.
Since VFPA reports the correct values in OS() too, the separate test for VAL(VERSION(4)) <= 9 is propably also redundant at this point according to [http://www.baiyujia.com/vfpdocuments/f_vfp9fix13.asp](http://www.baiyujia.com/vfpdocuments/f_vfp9fix13.asp). Since I didn't verify it because I'm not using VFPA I left it in.

**Comment by ggreen86** [comment]
This will be added to the next release.

________________________________
From: Starfiresg1 ***@***.***>
Sent: Wednesday, June 30, 2021 3:26 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Support Windows 10 in AddFilesToZip (#57)


In order to properly detect Windows 10 I had to make the following change to AddFilesToZip:

Old:
IF VAL(VERSION(4)) <= 9 .AND. (OS(3)<'6' .OR. OS(3)='6' .AND. OS(4)<'1')

New:
IF VAL(VERSION(4)) <= 9 .AND. (VAL(OS(3))<6 .OR. VAL(OS(3))=6 .AND. VAL(OS(4))<1)

Background:
While by default OS() will not report the correct information under Windows 10, it is possible to make it report the correct values for Windows 10, e.g. OS(3)='10', if the app is using an application manifest declaring itself Windows 10 aware.
This is propably due to Foxpro using the GetVersionEx-API to determine this value - starting with Windows 8.1 this API will only report Windows 8 numbers unless the manifest specifies comaptibility with higher Windows versions - see https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa.

The comparison fails then because the values are compared as strings - which results in '10'<'6' as evaluating as .T.. Casting the results to numerical values and comparing numerically will fix this.
Since VFPA reports the correct values in OS() too, the separate test for VAL(VERSION(4)) <= 9 is propably also redundant at this point according to http://www.baiyujia.com/vfpdocuments/f_vfp9fix13.asp. Since I didn't verify it because I'm not using VFPA I left it in.

**Comment by ggreen86** [comment]
This fix has been added to Release 33 beta 10.  Thank you for the submission!
