### ISSUE TITLE
Maximum length of a sheet name

### ISSUE THREAD

**Issue by DougHennig** [ggreen86/XLSX-Workbook-Class#60]
The maximum length of a sheet name is 31, not 30, characters, so in my copy, I changed the value of the LIMITS_MAX_SH_NAME constant in VFPXWorkbookXLSX.h

**Comment by ggreen86** [comment]
A quick 'Google' of the length confirms your setting.  Not sure why I had set it for 30 instead of 31...  Anyway, I will also update my defines file as well.

________________________________
From: Doug Hennig ***@***.***>
Sent: Tuesday, July 20, 2021 10:27 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Maximum length of a sheet name (#60)


The maximum length of a sheet name is 31, not 30, characters, so in my copy, I changed the value of the LIMITS_MAX_SH_NAME constant in VFPXWorkbookXLSX.h

**Comment by ggreen86** [comment]
The include file has been corrected.
