### ISSUE TITLE
Question about basic steps to convert XLS file to XLSX

### ISSUE THREAD

**Issue by nmossvfp** [ggreen86/XLSX-Workbook-Class#77]
Hi Greg,

Is there is a simple demo for conversion of an .XLS file to an .XLSX file using the XLSX-Workbook Class ?
m.xfile = "c:\data\myfile.xls"
m.newfile = "c:\data\myfile.xlsx"

I use your class and am grateful for your work but I have even more queries which I rely on that use the native VFP Copy TO XLS command.   Recently, this has become more and more of an issue for me as clients lock down the .XLS file type with read-only and strong warning message due to it's infrequent use nowadays.

**Comment by jhernancanom** [comment]
Colleague:
You are confused about this library.

With this library you can convert a cursor/DBF/table/grid to an XLSx spreadsheet.

What you need to do is change the VFP' **_COPY TO_** command in you application for one of the following _VFPxWorkbookXlsx_'s functions.

You can use any of this functions (you can see them in the documentation):


**SaveGridToWorkbook** 
Saves the passed grid to a workbook in xlsx file format. Uses the grid
column widths to set the workbook column widths. Adds a new sheet
for each passed grid if the same workbook name.

**SaveGridToWorkbookEx** 
Saves the passed grid to a workbook in xlsx file format by writing
directly to the XLSX files and does not write to the internal cursors;
hence, this is the fastest way to create a XLSX file from a grid.

**SaveTableToWorkbook** 
Saves the passed table to a workbook in xlsx file format. Adds a new
sheet for each passed table if the same workbook name.

**SaveTableToWorkbookEx** 
Saves the passed table to a workbook in xlsx file format by writing
directly to the XLSX files and does not write to the internal cursors;
hence, this is the fastest way to create a XLSX file from a table or
cursor. You can also pass an array of the fields that are to be included
in the export.

**SaveWorkbook** 
Saves the selected workbook to xlsx file format based on the name set
at creation of the workbook

**SaveWorkbookAs** 
Saves the selected workbook to xlsx file format with the supplied file
name; resets the workbook file name for future saves

**Comment by ggreen86** [comment]
Hello--

The XLS format is not supported by the workbook class as it is not based on xml.  As such, the class cannot open the xls workbook.  You would need to use automation of Excel or other methods to read the workbook.

Greg
________________________________
From: nmossvfp ***@***.***>
Sent: Tuesday, December 27, 2022 5:14 PM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Question about basic steps to convert XLS file to XLSX (Issue #77)


Hi Greg,

Is there is a simple demo for conversion of an .XLS file to an .XLSX file using the XLSX-Workbook Class ?
m.xfile = "c:\data\myfile.xls"
m.newfile = "c:\data\myfile.xlsx"

I use your class and am grateful for your work but I have even more queries which I rely on that use the native VFP Copy TO XLS command. Recently, this has become more and more of an issue for me as clients lock down the .XLS file type with read-only and strong warning message due to it's infrequent use nowadays.

**Comment by nmossvfp** [comment]
>>> The XLS format is not supported by the workbook class <<<

Ok.  That makes sense and is something I didn’t realize.

 

Also as jhernancanom suggested in an earlier answer reply (Thanks) I can add run the same data query that would have produced the XLS output but instead of COPY TO XLS, I can use SaveTableToWorkbook function in XLSX Workbook class and create my .XLSX that way.  Is that basically correct?

**Comment by ggreen86** [comment]
Yes, you can save a cursor or table to a XLSX format using the method.
________________________________
