### ISSUE TITLE
Number As Text warning

### ISSUE THREAD

**Issue by ARuddOS** [ggreen86/XLSX-Workbook-Class#88]
Hi,

I cannot see anything in the release notes that would allow the suppression of "Number As Text warnings" on cells, but that may be just because I cannot see it rather than it not being there!

Is there any way to suppress these warnings?  In Excel automation it can be done cell be cell, and it has to be by cell by cell as far as I have found, this command would remove the error in cell A1:

m.oExcel = CREATEOBJECT("Excel.Application")
m.oExcel.WorkBooks.Add()
m.oExcel.WorkBooks(1).Sheets(1).Cells(1,1).Errors(3).Ignore=.T.

Is there an equivalent in your class please?

Thanks

Adam

**Comment by ggreen86** [comment]
Adam—

Currently there is not a method that will set the cell to ignore the warning message.  I have created a test spreadsheet with the warning set to be ignored and it does not appear to be difficult to add this feature.  Cannot make any promises, but I will look into adding this for the next beta release.

Greg

From: ARuddOS ***@***.***>
Sent: Monday, June 12, 2023 10:08 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] Number As Text warning (Issue #88)


Hi,

I cannot see anything in the release notes that would allow the suppression of "Number As Text warnings" on cells, but that may be just because I cannot see it rather than it not being there!

Is there any way to suppress these warnings? In Excel automation it can be done cell be cell, and it has to be by cell by cell as far as I have found, this command would remove the error in cell A1:

m.oExcel = CREATEOBJECT("Excel.Application")
m.oExcel.WorkBooks.Add()
m.oExcel.WorkBooks(1).Sheets(1).Cells(1,1).Errors(3).Ignore=.T.

Is there an equivalent in your class please?

Thanks

Adam

**Comment by ARuddOS** [comment]
Thanks, it would be much appreciated, as is the class in general, so much quicker creating xlsx files than doing the same via Excel automation.

We are planning to use your class to create spreadsheets from our billing software, the invoice numbers are text but are predominantly numbers with leading zeros.  We set the cell format to be text so that Excel shows the leading zeros, and then it is fairly niche but I personally find the little green flag on each cell with the warning to be distracting!

**Comment by ggreen86** [comment]
Adam—

I have added a new method (SetIgnoreWarnings) to assign the ignore for a cell in Beta 4.  See the Demo() method, line 174 for some examples of calling the method.  Please perform some testing to set the ignore setting and let me know if it works.  If you have any problems, please send an example spreadsheet for me to debug.  Thank you.

Greg

**Comment by ARuddOS** [comment]
Brilliant, thanks!  That works well for me for the NumberAsText warnings.

If I may suggest one tweak that may be useful, there are several warnings that can be suppressed and other users may want to suppress other types too.

This is the full list:
https://learn.microsoft.com/en-us/office/vba/api/Excel.XlErrorChecks

Now I see the list I think the XlTextDate may also be useful for us where our users have entered a date in a free text field in our system.  Not a biggie though, we do not suppress that one through Excel Automation at the moment.
