### ISSUE TITLE
rtl and ltr

### ISSUE THREAD

**Issue by RezaUzer** [ggreen86/XLSX-Workbook-Class#94]
Dear Greg,
Is it possible to change sheet direction from rtl to ltr and vice versa?

**Comment by ggreen86** [comment]
Please provide me a sample workbook so that I can analyze it for RTL layout requirements.

From: RezaUzer ***@***.***>
Sent: Wednesday, August 9, 2023 11:36 AM
To: ggreen86/XLSX-Workbook-Class ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/XLSX-Workbook-Class] rtl and ltr (Issue #94)


Dear Greg,
Is it possible to change sheet direction from rtl to ltr and vice versa?

**Comment by RezaUzer** [comment]
Sheet Right-to-Left option in the Page Leyout menu in Excel.
![001](https://github.com/ggreen86/XLSX-Workbook-Class/assets/135454886/cc8d101c-35cc-4bb5-a52f-984ed8cdf790)
![002](https://github.com/ggreen86/XLSX-Workbook-Class/assets/135454886/aec525d6-9a99-46ff-aec0-bd5dc5e10ee7)

**Comment by ggreen86** [comment]
I have added support for Right-to-Left layout to the AddSheet method.  There is a new parameter added.  Please see Release 39 Beta 11 for the change.

**Comment by RezaUzer** [comment]
I use the following commands to convert the grid to Excel. In this case, how do I turn the page right to left?

           LOCAL lcExcel, lnWB, lcSheet, loReturn
           
           lcExcel = "D:\sample01.xlsx"
           lcSheet = "sheet1"
           
           thisform.clsVFPxWorkbookXLSX.SaveGridToWorkbookEx(thisform.Grid1, lcExcel, .F., lcSheet)
           
           lnWB = thisform.clsVFPxWorkbookXLSX.OpenXLSXWorkbook(lcExcel)
           lnWS = thisform.clsVFPxWorkbookXLSX.GetSheetIndex(lnWB, lcSheet)
              
           AddRow = thisform.clsVFPxWorkbookXLSX.InsertRow(lnWB, lnWS, 1, "BEFORE")
              
           thisform.clsVFPxWorkbookXLSX.SaveWorkbook(lnWb)
              
           WAIT WINDOW "Saved To Excel" NOWAIT
